Update home page content
osu-uwaterloo/osu-uwaterloo-website pull request #15
Opened 2024-01-03 06:59 UTC by danielq987

![image](https://github.com/osu-uwaterloo/osu-uwaterloo-website/assets/67433232/36d28c5a-63e3-42c4-9d7c-d357a4757c31)
^^ side-by-side (left: old, right: new)

- Added an image (its perpetualcolor for now)
- Added how to join section
- Made existing sections less verbose

I would appreciate feedback, especially from execs (regarding content).

2024-01-04 22:18 UTC, yfxu requested changes
Yea I like this about page much better than what I originally wrote XD

2024-01-04 22:18 UTC, yfxu commented on content/about/_index.md
> +osu!UWaterloo officially meets in-person bi-weekly, usually on Saturday 2-6pm at [PHYS 145](https://maps.app.goo.gl/eYAM98mDbcBJEHG8A). Please check the announcements channel in the Discord server to
maybe we can style "announcements" similar to how `#verification` was done:

"announcements" -> "`#announcements`"

2024-01-04 22:18 UTC, yfxu commented on content/about/_index.md
> +Please contact `pikapwn` on Discord if you are interested in competing.
Thoughts on changing `pikapwn` to `@pikapwn`?

2024-01-05 00:06 UTC, yfxu approved these changes
let's go

2024-01-05 00:06 UTC, yfxu commented on static/images/perpet.jpg
Oh yea is there a copy of this image with larger dimensions? In the screenshot in the PR, the image doesn't span the entire width, and I feel like it'd look better if it did.

We could achieve that with either a CSS rule to set `img { width: 100%; }` with some more precise rules to only affect images in posts, or just get a larger image.

2024-01-05 04:54 UTC, danielq987 commented on static/images/perpet.jpg
i purposely made the image smaller to fit inside the container LOL but yeah i added a css rule so that the image width is always 100% yay

2024-01-05 04:54 UTC, merged